package `in`.iot.lab.iotlabattendance.feature_home.data.model

/**
 * This is the structure of each Attendance Data
 *
 * @param id Auto generated by the Database
 * @param in_time In time on which the user entered the Lab
 * @param out_time Time on which the user left the Lab
 * @param roll Roll No. of the person
 */
data class AttendanceData(
    val id: String,
    val in_time: String?,
    val out_time: String?,
    val roll: String
)